import { Html, Head, Main, NextScript } from "next/document";

const Document = () => {
  return (
    <Html>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* animate.css */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>
      <body>
        <Main />
        {/* React Portals */}
        <div id="modal" />
        <div id="drawer" />
        <div id="dialog" />
        {/* React Portals */}

        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
