import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import toast from "react-hot-toast";
import Modal from "@/components/ui/Modal";
import { useState } from "react";

export default function Home() {
  const [showModal, setShowModal] = useState(true);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => setShowModal(!showModal)}>
        {showModal ? "Exit" : "Show"} Modal
      </button>
      <Modal show={showModal} onClose={() => setShowModal(false)}>
        <div className="w-full md:w-[400px]">
          <p>Something to describe</p>
          <button
            className="border rounded p-2 mt-4"
            onClick={() => {
              toast.promise(
                new Promise((resolve, reject) => {
                  setTimeout(() => {
                    reject(true);
                  }, 5000);
                }),
                {
                  loading: "Loading",
                  success: "Got the data",
                  error: "Error when fetching",
                }
              );
            }}
          >
            Show Toast
          </button>
        </div>
      </Modal>

      <button
        onClick={() => {
          toast.promise(
            new Promise((resolve, reject) => {
              setTimeout(() => {
                reject(true);
              }, 5000);
            }),
            {
              loading: "Loading",
              success: "Got the data",
              error: "Error when fetching",
            }
          );
        }}
      >
        Show Toast
      </button>
    </div>
  );
}
